language: node_js

node_js:
  - 12

notifications:
  email: false

branches:
  only:
    - main

script:
  - echo "test if deploy"
  - LATEST_COMMIT=$(git log -1 --format=format:%H --full-diff .)

before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0

deploy:
  - provider: heroku
    api_key: $HEROKU_KEY
    app: algotypes-bot
    on:
      condition: $DEPLOY_BOT = true
