language: node_js

node_js:
  - 12

notifications:
  email: false

branches:
  only:
    - master

script:
  - echo "test if deploy"
  - LATEST_COMMIT=$(git log -1 --format=format:%H --full-diff .)
  - LATEST_BOT_COMMIT=$(git log -1 --format=format:%H --full-diff ./algotypes_bot)
  - |
    if [[ $LATEST_COMMIT == $LATEST_BOT_COMMIT ]]
    then
      echo "Deploy Heroku"
      DEPLOY_BOT=true
    fi

before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
  - |
    if [[ $DEPLOY_BOT = true ]]
    then
      echo "Deploy Bots"
      cd algotypes_bot
    fi

deploy:
  - provider: heroku
    api_key: $HEROKU_KEY
    app: algotypes-bot
    on:
      condition: $DEPLOY_BOT = true
